Es6
digitalbazaar/bedrock-examples pull request #3
Opened 2017-07-06 14:40 UTC by jeiholzer

2017-08-14 17:48 UTC, dlongley requested changes
I think this PR looks good, but I would recommend one more change that's important for people who copy these examples: Every use of `var` should be replaced with `const` (or `let` if and only if the variable is not initialized immediately or is reassigned).

2017-08-14 17:49 UTC, dlongley commented
We'll want to squash all of those `upgrade files` commits as well -- when we're ready to merge.

2017-08-14 17:57 UTC, mattcollier commented
@davidlehn @msporny @jeiholzer @dlongley on the topic of the use of `const`.  I recently updated the eslint rules to help us with this.  Eslint will return an error if `const` has been used incorrectly (variable has been reassigned).

https://github.com/digitalbazaar/bedrock-dev/commit/8a421b612a3f337ba14df87535a5515f2bdb8db1

Eslint will also recommend that `const` be used when possible.  There are some additional settings related to this behavior surrounding destructuring which we can look into later.

http://eslint.org/docs/rules/prefer-const

2017-09-07 16:14 UTC, dlongley commented
The skinned component in the advanced-skin example was lost in the latest commit that was about changing `var` to `const`. Was that intentional?

2017-09-07 16:28 UTC, mattcollier commented
@jeiholzer Please review convention wrt commit messages: https://github.com/digitalbazaar/bedrock/blob/master/CONTRIBUTING.md#commit-messages

2017-09-11 15:02 UTC, dlongley approved these changes
LGTM other than fixing up commit messages and doing some squashing (without losing authorship). @mattcollier  can you work with @jeiholzer on that (the squashing)?

2017-09-19 16:47 UTC, jeiholzer commented
@dlongley @mattcollier @dlehn all comments have been addressed; ready for another review

2017-09-19 22:33 UTC, mattcollier commented
@jeiholzer some comments have not been addressed, one in `express-route-override/config.js` and one in `advanced-skin/components/register-service.js` also, other that you have `show outdated` to see.

You should be looking at the `conversation` tab here: https://github.com/digitalbazaar/bedrock-examples/pull/3

2017-09-21 19:07 UTC, mattcollier commented on advanced-skin/components/register-service.js
>  function factory() {
combine what's on L16 here with
```
export default function factory () {
```

2017-09-21 19:07 UTC, mattcollier commented on express-route-override/components/main.js
> +import angular from 'angular';
The new convention for this file is to call it `index.js`.  And in the package.json file, for modules like these that are both nodejs and front-end, the `main` property points to the nodesjs index.js (typically './lib/index.js') and the `browser` property points to the `index.js` in `components`.  Typically:
```
{
  main: 'lib',
  browser: 'index.js'
}
```

2017-09-21 19:07 UTC, mattcollier commented on express-route-override/config.js
> +config.views.system.importAllIgnore.push('bootstrap');
we shouldn't need this anywhere anymore as this was a work around.  If boostrap is a requirement you'll want to use: https://github.com/digitalbazaar/bedrock-angular-bootstrap and not have a direct bootstrap dependency anywher.

2017-09-21 19:07 UTC, mattcollier commented on angular-basic/lib/config.js
>  // angular-basic pseudo bower package
`pseudo bower package` is no longer a thing.  Change this to `pseudo package` everywhere.

2017-09-21 19:07 UTC, mattcollier commented on advanced-skin/components/password-confirmation-directive.js
> +export default function factory($timeout) {
@jeiholzer this directive can eliminated here.  We have added a directive in bedrock-angular-form that does the same thing.   You can see how it's implemented here:

https://github.com/digitalbazaar/bedrock-angular-authn-password/blob/material/password-reset-component.html#L34

https://github.com/digitalbazaar/bedrock-angular-form/blob/master/validator-same-as-directive.js

2017-09-25 13:43 UTC, jeiholzer commented
I think everything has been addressed but I did leave config.views.system.importAllIgnore.push('bootstrap'); in basic-modals-example because even when switching to using #material branch it got to a point where the example worked but not with modals.It seemed better to not rely on branches that will eventually go away. Will update when '#material' work is done. Let me know if you disagree.

2017-10-05 19:46 UTC, jeiholzer commented
Ok, I think I have addressed everything and modified the appropriate examples I was working on to Angular Material

2017-10-13 17:22 UTC, dlongley commented
@jeiholzer,

This PR needs conflict resolution then I believe it's ready to be merged in.

cc: @mattcollier

2017-10-23 19:04 UTC, merged